### ISSUE TITLE
Ctrl-c panic while running

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#1833]
```
[2018-08-31T12:17:17+08:00] WARN [daemon]: Waited 1.002675303s while waiting for daemon.Gateway.GetBlockchainProgress to be done or quit
[2018-08-31T12:17:18+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 185.799018ms
[2018-08-31T12:17:18+08:00] INFO [daemon:CRITICAL]: Added new block 55553
[2018-08-31T12:17:18+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 183.90448ms
[2018-08-31T12:17:18+08:00] INFO [daemon:CRITICAL]: Added new block 55554
[2018-08-31T12:17:18+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 160.922916ms
[2018-08-31T12:17:18+08:00] INFO [daemon:CRITICAL]: Added new block 55555
[2018-08-31T12:17:18+08:00] WARN [daemon]: Waited 2.004261369s while waiting for daemon.Gateway.GetConnections to be done or quit
[2018-08-31T12:17:18+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 176.009497ms
[2018-08-31T12:17:18+08:00] INFO [daemon:CRITICAL]: Added new block 55556
[2018-08-31T12:17:18+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 261.821552ms
[2018-08-31T12:17:18+08:00] INFO [daemon:CRITICAL]: Added new block 55557
^C[2018-08-31T12:17:18+08:00] INFO [main]: Shutting down...
[2018-08-31T12:17:18+08:00] INFO [main]: Closing web interface
[2018-08-31T12:17:18+08:00] INFO [api]: Shutting down web interface
[2018-08-31T12:17:18+08:00] INFO [api]: Web interface closed
[2018-08-31T12:17:18+08:00] ERROR [main]: accept tcp 127.0.0.1:6420: use of closed network connection
[2018-08-31T12:17:18+08:00] INFO [api]: Web interface shut down
[2018-08-31T12:17:18+08:00] INFO [main]: Closing daemon
[2018-08-31T12:17:18+08:00] INFO [daemon]: Stopping the daemon run loop
[2018-08-31T12:17:18+08:00] INFO [daemon]: Shutting down Pool
[2018-08-31T12:17:18+08:00] INFO [gnet]: ConnectionPool.Shutdown called
[2018-08-31T12:17:18+08:00] INFO [gnet]: ConnectionPool.Shutdown closed pool.quit
[2018-08-31T12:17:18+08:00] INFO [gnet]: ConnectionPool.Shutdown waiting for strandDone
[2018-08-31T12:17:18+08:00] INFO [gnet]: ConnectionPool.Shutdown closing the listener
[2018-08-31T12:17:18+08:00] INFO [gnet]: ConnectionPool.Shutdown disconnecting all connections
[2018-08-31T12:17:18+08:00] DEBUG [gnet]: Connection 118.178.135.93:6000 closed
[2018-08-31T12:17:18+08:00] ERROR [gnet]: conn.Close() error address=118.178.135.93:6000: close tcp 192.168.0.2:49563->118.178.135.93:6000: use of closed network connection
[2018-08-31T12:17:18+08:00] INFO [gnet]: ConnectionPool.Shutdown waiting for done
[2018-08-31T12:17:18+08:00] INFO [gnet]: Connection pool closed
[2018-08-31T12:17:18+08:00] INFO [daemon]: Shutting down Gateway
[2018-08-31T12:17:18+08:00] INFO [daemon]: Shutting down Pex
[2018-08-31T12:17:18+08:00] INFO [pex]: Shutting down pex
[2018-08-31T12:17:18+08:00] INFO [api]: 200 GET /api/v1/blockchain/progress 1.975549219s
[2018-08-31T12:17:18+08:00] INFO [pex]: Save peerlist
2018/08/31 12:17:18 http: panic serving 127.0.0.1:49597: runtime error: invalid memory address or nil pointer dereference
goroutine 160 [running]:
net/http.(*conn).serve.func1(0xc00052aa00)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0x15cc760, 0x1bdc5c0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/skycoin/skycoin/src/api.connectionsHandler.func1(0x1724960, 0xc000136480, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/network.go:77 +0xdd
net/http.HandlerFunc.ServeHTTP(0xc0004dc220, 0x1724960, 0xc000136480, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.ElapsedHandler.func1(0x1725560, 0xc00027e5a0, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/log.go:17 +0x100
net/http.HandlerFunc.ServeHTTP(0xc0004d45d0, 0x1725560, 0xc00027e5a0, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.CSRFCheck.func1(0x1725560, 0xc00027e5a0, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:141 +0x1d6
net/http.HandlerFunc.ServeHTTP(0xc0004dc240, 0x1725560, 0xc00027e5a0, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.OriginRefererCheck.func1(0x1725560, 0xc00027e5a0, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:175 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc0004d4600, 0x1725560, 0xc00027e5a0, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.HostCheck.func1(0x1725560, 0xc00027e5a0, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/handler.go:50 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc0004e4200, 0x1725560, 0xc00027e5a0, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x17253e0, 0xc000638460, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler/gzip.go:287 +0x1a6
net/http.HandlerFunc.ServeHTTP(0xc0004d4660, 0x17253e0, 0xc000638460, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0003b25d0, 0x17253e0, 0xc000638460, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0004b5ad0, 0x17253e0, 0xc000638460, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00052aa00, 0x1725a20, 0xc0004e46c0)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2851 +0x2f5
[2018-08-31T12:17:18+08:00] INFO [pex]: Pex.Run stopped
[2018-08-31T12:17:18+08:00] INFO [pex]: Pex shutdown
2018/08/31 12:17:18 http: panic serving 127.0.0.1:49598: runtime error: invalid memory address or nil pointer dereference
goroutine 260 [running]:
net/http.(*conn).serve.func1(0xc000635860)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0x15cc760, 0x1bdc5c0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/skycoin/skycoin/src/api.connectionsHandler.func1(0x1724960, 0xc000136400, 0xc000112600)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/network.go:77 +0xdd
net/http.HandlerFunc.ServeHTTP(0xc0004dc220, 0x1724960, 0xc000136400, 0xc000112600)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.ElapsedHandler.func1(0x1725560, 0xc000098780, 0xc000112600)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/log.go:17 +0x100
net/http.HandlerFunc.ServeHTTP(0xc0004d45d0, 0x1725560, 0xc000098780, 0xc000112600)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.CSRFCheck.func1(0x1725560, 0xc000098780, 0xc000112600)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:141 +0x1d6
net/http.HandlerFunc.ServeHTTP(0xc0004dc240, 0x1725560, 0xc000098780, 0xc000112600)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.OriginRefererCheck.func1(0x1725560, 0xc000098780, 0xc000112600)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:175 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc0004d4600, 0x1725560, 0xc000098780, 0xc000112600)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.HostCheck.func1(0x1725560, 0xc000098780, 0xc000112600)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/handler.go:50 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc0004e4200, 0x1725560, 0xc000098780, 0xc000112600)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x17253e0, 0xc0003429a0, 0xc000112600)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler/gzip.go:287 +0x1a6
net/http.HandlerFunc.ServeHTTP(0xc0004d4660, 0x17253e0, 0xc0003429a0, 0xc000112600)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0003b25d0, 0x17253e0, 0xc0003429a0, 0xc000112600)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0004b5ad0, 0x17253e0, 0xc0003429a0, 0xc000112600)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000635860, 0x1725a20, 0xc0004e4c40)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2851 +0x2f5
2018/08/31 12:17:18 http: panic serving 127.0.0.1:49588: runtime error: invalid memory address or nil pointer dereference
goroutine 170 [running]:
net/http.(*conn).serve.func1(0xc00019fb80)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0x15cc760, 0x1bdc5c0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/skycoin/skycoin/src/api.connectionsHandler.func1(0x1724960, 0xc000136280, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/network.go:77 +0xdd
net/http.HandlerFunc.ServeHTTP(0xc0004dc220, 0x1724960, 0xc000136280, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.ElapsedHandler.func1(0x1725560, 0xc000125500, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/log.go:17 +0x100
net/http.HandlerFunc.ServeHTTP(0xc0004d45d0, 0x1725560, 0xc000125500, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.CSRFCheck.func1(0x1725560, 0xc000125500, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:141 +0x1d6
net/http.HandlerFunc.ServeHTTP(0xc0004dc240, 0x1725560, 0xc000125500, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.OriginRefererCheck.func1(0x1725560, 0xc000125500, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:175 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc0004d4600, 0x1725560, 0xc000125500, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.HostCheck.func1(0x1725560, 0xc000125500, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/handler.go:50 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc0004e4200, 0x1725560, 0xc000125500, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x17253e0, 0xc000342460, 0xc000112200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler/gzip.go:287 +0x1a6
net/http.HandlerFunc.ServeHTTP(0xc0004d4660, 0x17253e0, 0xc000342460, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0003b25d0, 0x17253e0, 0xc000342460, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0004b5ad0, 0x17253e0, 0xc000342460, 0xc000112200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00019fb80, 0x1725a20, 0xc000250200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2851 +0x2f5
2018/08/31 12:17:18 http: panic serving 127.0.0.1:49587: runtime error: invalid memory address or nil pointer dereference
goroutine 197 [running]:
net/http.(*conn).serve.func1(0xc000634dc0)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0x15cc760, 0x1bdc5c0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/skycoin/skycoin/src/api.connectionsHandler.func1(0x1724960, 0xc000136500, 0xc000112300)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/network.go:77 +0xdd
net/http.HandlerFunc.ServeHTTP(0xc0004dc220, 0x1724960, 0xc000136500, 0xc000112300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.ElapsedHandler.func1(0x1725560, 0xc000125860, 0xc000112300)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/log.go:17 +0x100
net/http.HandlerFunc.ServeHTTP(0xc0004d45d0, 0x1725560, 0xc000125860, 0xc000112300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.CSRFCheck.func1(0x1725560, 0xc000125860, 0xc000112300)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:141 +0x1d6
net/http.HandlerFunc.ServeHTTP(0xc0004dc240, 0x1725560, 0xc000125860, 0xc000112300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.OriginRefererCheck.func1(0x1725560, 0xc000125860, 0xc000112300)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:175 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc0004d4600, 0x1725560, 0xc000125860, 0xc000112300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.HostCheck.func1(0x1725560, 0xc000125860, 0xc000112300)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/handler.go:50 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc0004e4200, 0x1725560, 0xc000125860, 0xc000112300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x17253e0, 0xc0003435e0, 0xc000112300)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler/gzip.go:287 +0x1a6
net/http.HandlerFunc.ServeHTTP(0xc0004d4660, 0x17253e0, 0xc0003435e0, 0xc000112300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0003b25d0, 0x17253e0, 0xc0003435e0, 0xc000112300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0004b5ad0, 0x17253e0, 0xc0003435e0, 0xc000112300)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000634dc0, 0x1725a20, 0xc00015e400)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2851 +0x2f5
2018/08/31 12:17:18 http: panic serving 127.0.0.1:49586: runtime error: invalid memory address or nil pointer dereference
goroutine 184 [running]:
net/http.(*conn).serve.func1(0xc000634be0)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0x15cc760, 0x1bdc5c0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/skycoin/skycoin/src/api.connectionsHandler.func1(0x1724960, 0xc00013a300, 0xc0001d6200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/network.go:77 +0xdd
net/http.HandlerFunc.ServeHTTP(0xc0004dc220, 0x1724960, 0xc00013a300, 0xc0001d6200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.ElapsedHandler.func1(0x1725560, 0xc000152240, 0xc0001d6200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/log.go:17 +0x100
net/http.HandlerFunc.ServeHTTP(0xc0004d45d0, 0x1725560, 0xc000152240, 0xc0001d6200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.CSRFCheck.func1(0x1725560, 0xc000152240, 0xc0001d6200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:141 +0x1d6
net/http.HandlerFunc.ServeHTTP(0xc0004dc240, 0x1725560, 0xc000152240, 0xc0001d6200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.OriginRefererCheck.func1(0x1725560, 0xc000152240, 0xc0001d6200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:175 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc0004d4600, 0x1725560, 0xc000152240, 0xc0001d6200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.HostCheck.func1(0x1725560, 0xc000152240, 0xc0001d6200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/handler.go:50 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc0004e4200, 0x1725560, 0xc000152240, 0xc0001d6200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x17253e0, 0xc000638460, 0xc0001d6200)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler/gzip.go:287 +0x1a6
net/http.HandlerFunc.ServeHTTP(0xc0004d4660, 0x17253e0, 0xc000638460, 0xc0001d6200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0003b25d0, 0x17253e0, 0xc000638460, 0xc0001d6200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0004b5ad0, 0x17253e0, 0xc000638460, 0xc0001d6200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000634be0, 0x1725a20, 0xc00015e480)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2851 +0x2f5
2018/08/31 12:17:18 http: panic serving 127.0.0.1:49585: runtime error: invalid memory address or nil pointer dereference
goroutine 182 [running]:
net/http.(*conn).serve.func1(0xc000634280)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0x15cc760, 0x1bdc5c0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/skycoin/skycoin/src/api.connectionsHandler.func1(0x1724960, 0xc000136800, 0xc000112700)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/network.go:77 +0xdd
net/http.HandlerFunc.ServeHTTP(0xc0004dc220, 0x1724960, 0xc000136800, 0xc000112700)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.ElapsedHandler.func1(0x1725560, 0xc000125b60, 0xc000112700)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/log.go:17 +0x100
net/http.HandlerFunc.ServeHTTP(0xc0004d45d0, 0x1725560, 0xc000125b60, 0xc000112700)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.CSRFCheck.func1(0x1725560, 0xc000125b60, 0xc000112700)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:141 +0x1d6
net/http.HandlerFunc.ServeHTTP(0xc0004dc240, 0x1725560, 0xc000125b60, 0xc000112700)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/api.OriginRefererCheck.func1(0x1725560, 0xc000125b60, 0xc000112700)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/api/csrf.go:175 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc0004d4600, 0x1725560, 0xc000125b60, 0xc000112700)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/src/util/http.HostCheck.func1(0x1725560, 0xc000125b60, 0xc000112700)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/src/util/http/handler.go:50 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc0004e4200, 0x1725560, 0xc000125b60, 0xc000112700)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x17253e0, 0xc0003437a0, 0xc000112700)
	/Users/user/.gopath/src/github.com/skycoin/skycoin/vendor/github.com/NYTimes/gziphandler/gzip.go:287 +0x1a6
net/http.HandlerFunc.ServeHTTP(0xc0004d4660, 0x17253e0, 0xc0003437a0, 0xc000112700)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0003b25d0, 0x17253e0, 0xc0003437a0, 0xc000112700)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0004b5ad0, 0x17253e0, 0xc0003437a0, 0xc000112700)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000634280, 0x1725a20, 0xc00015e240)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2851 +0x2f5
[2018-08-31T12:17:18+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 153.163365ms
[2018-08-31T12:17:18+08:00] INFO [daemon:CRITICAL]: Added new block 55558
[2018-08-31T12:17:19+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 126.992673ms
[2018-08-31T12:17:19+08:00] INFO [daemon:CRITICAL]: Added new block 55559
[2018-08-31T12:17:19+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 131.452146ms
[2018-08-31T12:17:19+08:00] INFO [daemon:CRITICAL]: Added new block 55560
[2018-08-31T12:17:19+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 130.570419ms
[2018-08-31T12:17:19+08:00] INFO [daemon:CRITICAL]: Added new block 55561
[2018-08-31T12:17:19+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 132.009047ms
[2018-08-31T12:17:19+08:00] INFO [daemon:CRITICAL]: Added new block 55562
[2018-08-31T12:17:19+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 237.039222ms
[2018-08-31T12:17:19+08:00] INFO [daemon:CRITICAL]: Added new block 55563
[2018-08-31T12:17:19+08:00] DEBUG [dbutil]: db.Update [ExecuteSignedBlock] elapsed 244.338571ms
[2018-08-31T12:17:19+08:00] INFO [daemon:CRITICAL]: Added new block 55564
[2018-08-31T12:17:19+08:00] WARN [daemon]: Broadcast AnnounceBlocksMessage failed error="Connection pool is closed"
[2018-08-31T12:17:19+08:00] WARN [daemon]: Broadcast GetBlocksMessage failed error="Connection pool is closed"
[2018-08-31T12:17:19+08:00] WARN [daemon]: dm.messageEvents elapsed 3.493499356s
[2018-08-31T12:17:19+08:00] INFO [daemon]: 18.179.56.163:6000 disconnected because: read data failed: EOF
[2018-08-31T12:17:19+08:00] INFO [daemon]: Daemon closed
[2018-08-31T12:17:19+08:00] INFO [daemon]: Daemon shutdown complete
[2018-08-31T12:17:19+08:00] INFO [main]: Waiting for goroutines to finish
[2018-08-31T12:17:19+08:00] INFO [main]: Closing database
[2018-08-31T12:17:19+08:00] INFO [main]: Goodbye
```

**Comment by gz-c** [comment]
I'm finding it difficult to replicate. It seems that the `strand` call in `GetBlockchainProgress` returned `nil, nil` which can only happen is strand() aborts early (maybe it was already closed?)

Looking at the log order, the API call for `/blockchain/progress` was made, but then was blocked by slow `ExecuteBlock` calls.  However, `ExecuteBlock` locks at the visor database layer and not at the gateway strand.

This problem should go away once we remove strand() (see #1808)

**Comment by gz-c** [comment]
strand was removed and i haven't seen this problem since
