### ISSUE TITLE
Electron Linux AppImage version has hardware-wallet dep error

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#2172]
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'hardware-wallet-js/device-wallet'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/tmp/.mount_skycoiwiFWSM/app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_skycoiwiFWSM/app/resources/app.asar/src/hardware-wallet.js:5:22)
    at Object.<anonymous> (/tmp/.mount_skycoiwiFWSM/app/resources/app.asar/src/hardware-wallet.js:224:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```

**Comment by Senyoret1** [comment]
I compiled a production version from the master branch using Linux and it opened correctly. Is that the correct branch or are there some specific steps for the error to appear?

**Comment by gz-c** [comment]
This is the build produced by the build system.

https://downloads.skycoin.net/wallet/skycoin-0.25.1-gui-electron-linux-x64.AppImage

If this version works for you, it may be that the dependencies on your system are being found

**Comment by Senyoret1** [comment]
For some reason the OS does not want to open it (it says that it can not open files with that extension, but it opens the locally compiled files with the same extension).

The differences I can see are that the locally compiled file has a size of 65.9Mb and the one on the link has a size of 65.6MB, and that the locally compiled file is called `skycoin-0.25.1-x86_64.AppImage` and the one on the link is called `skycoin-0.25.1-gui-electron-linux-x64.AppImage`.

Also, an interesting fact is that the error happens due to not being able to find the `hardware-wallet-js/device-wallet` which is installed with `npm install` and bundled with the app, so it is possible that it was an error when building the file.

**Comment by Senyoret1** [comment]
Oh, I was able to open it and saw the error. Taking into account that with a locally compiled version it worked well, I am inclined to think that it must have been an error when compiling the file.

**Comment by olemis** [comment]
@Senyoret1 if that was the case there should be a message in the Travis build that generated the release build artifacts 
@gz-c cmiiw

**Comment by gz-c** [comment]
The compilation did fail in travis, but it did not cause an overall failure. 

Build failure can be seen here:

https://api.travis-ci.org/v3/job/490960154/log.txt

```
[0K$ if [[ "$TRAVIS_PULL_REQUEST" == false ]]; then ./ci-scripts/build-wallet.sh; fi
start to build wallets...
~/gopath/src/github.com/skycoin/skycoin/electron ~/gopath/src/github.com/skycoin/skycoin
Compiling with gox
/home/travis/gopath/src/github.com/skycoin/skycoin/electron
Number of parallel builds: 1

-->     linux/amd64: github.com/skycoin/skycoin/cmd/skycoin
-->       linux/arm: github.com/skycoin/skycoin/cmd/skycoin
mkdir .gox_output/gui/linux_x64
mkdir .gox_output/gui/linux_arm
Installing node modules

> skycoin@0.25.1 postinstall /home/travis/gopath/src/github.com/skycoin/skycoin/electron
> electron-builder install-app-deps

  â€¢ electron-builder version=20.13.3
  â€¢ loaded configuration file=package.json ("build" field)
  â€¢ no native production dependencies
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN skycoin@0.25.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.8.6 (node_modules/app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.8.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.8.6 (node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.8.6: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 3.689s

> node-hid@0.7.3 install /home/travis/gopath/src/github.com/skycoin/skycoin/electron/src/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/gopath/src/github.com/skycoin/skycoin/electron/src/node_modules/node-hid/build/Release/HID.node)
make: Entering directory `/home/travis/gopath/src/github.com/skycoin/skycoin/electron/src/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/linux/hid.o
../hidapi/linux/hid.c:44:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
                     ^
compilation terminated.
make: *** [Release/obj.target/hidapi/hidapi/linux/hid.o] Error 1
make: Leaving directory `/home/travis/gopath/src/github.com/skycoin/skycoin/electron/src/node_modules/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v8.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v8.11.0/bin/node" "/home/travis/.nvm/versions/node/v8.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/gopath/src/github.com/skycoin/skycoin/electron/src/node_modules/node-hid
gyp ERR! node -v v8.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN src No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.7.3 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-02-09T14_27_39_901Z-debug.log

===========================
Building standalone release

===========================
Packaging standalone release
In package standalone release: linux/amd64 linux/arm
Copying skycoin binaries
Copying .gox_output/gui/linux_x64/skycoin to .standalone_output/skycoin-0.25.1-gui-standalone-linux-x64
Copying ../src/gui/static/dist to .standalone_output/skycoin-0.25.1-gui-standalone-linux-x64/src/gui/static
Copying CHANGELOG.md to .standalone_output/skycoin-0.25.1-gui-standalone-linux-x64
Adding .standalone_output/skycoin-0.25.1-gui-standalone-linux-x64/src to package-source.sh list
Copying .gox_output/gui/linux_arm/skycoin to .standalone_output/skycoin-0.25.1-gui-standalone-linux-arm
Copying ../src/gui/static/dist to .standalone_output/skycoin-0.25.1-gui-standalone-linux-arm/src/gui/static
Copying CHANGELOG.md to .standalone_output/skycoin-0.25.1-gui-standalone-linux-arm
Adding .standalone_output/skycoin-0.25.1-gui-standalone-linux-arm/src to package-source.sh list
------------------------------
Compressing standalone release
Zipping skycoin-0.25.1-gui-standalone-linux-x64.tar.gz
Zipping skycoin-0.25.1-gui-standalone-linux-arm.tar.gz

===========================
Building electron release

> skycoin@0.25.1 dist-linux /home/travis/gopath/src/github.com/skycoin/skycoin/electron
> build -l --x64 -p=never

  â€¢ electron-builder version=20.13.3
  â€¢ loaded configuration file=package.json ("build" field)
  â€¢ no native production dependencies
  â€¢ packaging       platform=linux arch=x64 electron=2.0.9 appOutDir=release/linux-unpacked
  â€¢ building        target=snap arch=x64 file=release/skycoin_0.25.1_amd64.snap
  â€¢ building        target=AppImage arch=x64 file=release/skycoin-0.25.1-x86_64.AppImage

===========================
Building daemon release
Number of parallel builds: 1

-->       linux/arm: github.com/skycoin/skycoin/cmd/skycoin
-->     linux/amd64: github.com/skycoin/skycoin/cmd/skycoin
mkdir .gox_output/daemon/linux_x64
mkdir .gox_output/daemon/linux_arm

===========================
Packaging daemon release
In package daemon release: linux/amd64 linux/arm
Copying skycoin binaries
Copying .gox_output/daemon/linux_x64/skycoin to .daemon_output/skycoin-0.25.1-daemon-linux-x64
Copying CHANGELOG.md to .daemon_output/skycoin-0.25.1-daemon-linux-x64
Adding .daemon_output/skycoin-0.25.1-daemon-linux-x64/src to package-source.sh list
Copying .gox_output/daemon/linux_arm/skycoin to .daemon_output/skycoin-0.25.1-daemon-linux-arm
Copying CHANGELOG.md to .daemon_output/skycoin-0.25.1-daemon-linux-arm
Adding .daemon_output/skycoin-0.25.1-daemon-linux-arm/src to package-source.sh list
------------------------------
Compressing daemon release
Zipping skycoin-0.25.1-daemon-linux-x64.tar.gz
Zipping skycoin-0.25.1-daemon-linux-arm.tar.gz

===========================
Building cli release
Number of parallel builds: 1

-->     linux/amd64: github.com/skycoin/skycoin/cmd/cli
-->       linux/arm: github.com/skycoin/skycoin/cmd/cli
mkdir .gox_output/cli/linux_x64
mkdir .gox_output/cli/linux_arm

===========================
Packaging cli release
In package cli release: linux/amd64 linux/arm
Copying skycoin-cli binaries
Copying .gox_output/cli/linux_x64/skycoin-cli to .cli_output/skycoin-0.25.1-cli-linux-x64
Copying CHANGELOG.md to .cli_output/skycoin-0.25.1-cli-linux-x64
Copying cmd/cli/README.md to .cli_output/skycoin-0.25.1-cli-linux-x64
Adding .cli_output/skycoin-0.25.1-cli-linux-x64/src to package-source.sh list
Copying .gox_output/cli/linux_arm/skycoin-cli to .cli_output/skycoin-0.25.1-cli-linux-arm
Copying CHANGELOG.md to .cli_output/skycoin-0.25.1-cli-linux-arm
Copying cmd/cli/README.md to .cli_output/skycoin-0.25.1-cli-linux-arm
Adding .cli_output/skycoin-0.25.1-cli-linux-arm/src to package-source.sh list
------------------------------
Compressing cli release
Zipping skycoin-0.25.1-cli-linux-x64.tar.gz
Zipping skycoin-0.25.1-cli-linux-arm.tar.gz
skycoin_0.25.1_amd64.snap
skycoin-0.25.1-cli-linux-arm.tar.gz
skycoin-0.25.1-cli-linux-x64.tar.gz
skycoin-0.25.1-daemon-linux-arm.tar.gz
skycoin-0.25.1-daemon-linux-x64.tar.gz
skycoin-0.25.1-gui-electron-linux-x64.AppImage
skycoin-0.25.1-gui-standalone-linux-arm.tar.gz
skycoin-0.25.1-gui-standalone-linux-x64.tar.gz
~/gopath/src/github.com/skycoin/skycoin
travis_time:end:0025cc44:start=1549722423517337444,finish=1549722537738819880,duration=114221482436
[0K[32;1mThe command "if [[ "$TRAVIS_PULL_REQUEST" == false ]]; then ./ci-scripts/build-wallet.sh; fi" exited with 0.[0m

travis_fold:start:cache.2
[0Kstore build cache
travis_time:start:1350d5b1
[0Ktravis_time:end:1350d5b1:start=1549722537745003935,finish=1549722537749990588,duration=4986653
[0Ktravis_time:start:1e4a4054
[0K[32;1mnothing changed, not updating cache[0m
travis_time:end:1e4a4054:start=1549722537754876738,finish=1549722541785289649,duration=4030412911
[0Ktravis_fold:end:cache.2
[0K
[33;1mSkipping a deployment with the s3 provider because this branch is not permitted: v0.25.1[0m
```
