### ISSUE TITLE
Bug: Skycoin-cli transaction command panics if zero args passes

### ISSUE THREAD

**Issue by BigOokie** [skycoin/skycoin#2348]
Following some testing of the `skycoin-cli` `transaction` command it appears that the application will panic if you don't pass any arguments. Examination of the code indicates it is expecting one argument to always be passed.

Example:
```bash
$ skycoin-cli transaction     
```

Result:
```bash            
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/skycoin/skycoin/src/cli.transactionCmd.func1(0xc0002c6a00, 0x1b51680, 0x0, 0x0, 0x0, 0x0)
        /Users/BigOokie/Documents/_Dev/go/src/github.com/skycoin/skycoin/src/cli/transaction.go:28 +0x1b0
github.com/skycoin/skycoin/vendor/github.com/spf13/cobra.(*Command).execute(0xc0002c6a00, 0x1b51680, 0x0, 0x0, 0xc0002c6a00, 0x1b51680)
        /Users/BigOokie/Documents/_Dev/go/src/github.com/skycoin/skycoin/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/skycoin/skycoin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000257180, 0x20, 0xc00027c3d0, 0xf)
        /Users/BigOokie/Documents/_Dev/go/src/github.com/skycoin/skycoin/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/skycoin/skycoin/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/BigOokie/Documents/_Dev/go/src/github.com/skycoin/skycoin/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /Users/BigOokie/Documents/_Dev/go/src/github.com/skycoin/skycoin/cmd/cli/cli.go:26 +0x18c
```

The issue appears to be with the `Args` validation (below):
https://github.com/skycoin/skycoin/blob/be14cd713717f6c359fecd796240b08b370c38c3/src/cli/transaction.go#L26

Which then causes the following line of code to fail:
https://github.com/skycoin/skycoin/blob/be14cd713717f6c359fecd796240b08b370c38c3/src/cli/transaction.go#L28

Instead of using `cobra.MaximumNArgs(1)` should use `cobra.ExactArgs(1)`

Testing the implementation of the `Transaction` API, it appears it requires a transaction ID to be specified otherwise it will respond with the following:
```
Error: 400 Bad Request - txid is empty
```

**Comment by BigOokie** [comment]
I will submit a PR shortly to address this small issue
