### ISSUE TITLE
Can not run web-interface

### ISSUE THREAD

**Issue by zesaver** [skycoin/skycoin#32]
Hello,

I tried to re-use skycoin after some period of inactivity and I got following:

- I can run gui but has the list only, without any buttons.
- I cannot run `$ tests.sh` or `$ ./run.sh -web-interface=true` successfully. Web-interface says following in terminal:
```
2015/03/16 15:00:36 Wallet Directory= /home/user/.skycoin/wallets
2015/03/16 15:00:36 Loaded wallet from /home/user/.skycoin/wallets/2015_03_16_9671.wlt
2015/03/16 15:00:36 L1
2015/03/16 15:00:36 L2
2015/03/16 15:00:36 L3
2015/03/16 15:00:36 L4
[skycoin.visor:DEBUG] Creating new visor
[skycoin.visor:INFO] Loaded serialized blockchain from "/home/user/.skycoin/blockchain.bin"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/skycoin/skycoin/src/visor.loadBlockchain(0xc2080a6510, 0x25, 0xada224d68cc97500, 0x2e77aa03beb6d750, 0xdd8b307b36, 0x0)
	/home/user/.gvm/pkgsets/go1.4/global/src/github.com/skycoin/skycoin/src/visor/serialization.go:81 +0x41b
github.com/skycoin/skycoin/src/visor.NewVisor(0x20f4d376c5280300, 0x3a1781a9582068e7, 0xbf55ffc57c4c374b, 0xe6bb5970f53c4d39, 0x6a45, 0x0, 0x0, 0x0, 0x0, 0xa, ...)
	/home/user/.gvm/pkgsets/go1.4/global/src/github.com/skycoin/skycoin/src/visor/visor.go:156 +0x19d
github.com/skycoin/skycoin/src/daemon.NewVisor(0x20f4d376c5280300, 0x3a1781a9582068e7, 0xbf55ffc57c4c374b, 0xe6bb5970f53c4d39, 0x6a45, 0x0, 0x0, 0x0, 0x0, 0xa, ...)
	/home/user/.gvm/pkgsets/go1.4/global/src/github.com/skycoin/skycoin/src/daemon/visor.go:54 +0x5a
github.com/skycoin/skycoin/src/daemon.NewDaemon(0x1, 0x0, 0x0, 0x16a6, 0x0, 0x0, 0x12a05f200, 0x12a05f200, 0x8, 0x10, ...)
	/home/user/.gvm/pkgsets/go1.4/global/src/github.com/skycoin/skycoin/src/daemon/daemon.go:225 +0x25b
main.Run(0x7f3d8c869970, 0xce4b60)
	/home/user/programs/skycoin/cmd/skycoin/skycoin.go:481 +0x289
main.main()
	/home/user/programs/skycoin/cmd/skycoin/skycoin.go:538 +0x51

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/user/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xd01100)
	/home/user/.gvm/pkgsets/go1.4/global/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/home/user/.gvm/pkgsets/go1.4/global/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 7 [syscall]:
os/signal.loop()
	/home/user/.gvm/gos/go1.4/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/home/user/.gvm/gos/go1.4/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [runnable]:
main.catchInterrupt(0xc2080523c0)
	/home/user/programs/skycoin/cmd/skycoin/skycoin.go:382
created by main.Run
	/home/user/programs/skycoin/cmd/skycoin/skycoin.go:471 +0xdf

goroutine 10 [runnable]:
main.catchDebug()
	/home/user/programs/skycoin/cmd/skycoin/skycoin.go:391
created by main.Run
	/home/user/programs/skycoin/cmd/skycoin/skycoin.go:473 +0xf0
exit status 2
```

Is this OK? Shoul it be possible to do anything in skycoin for the moment?

**Comment by skycoin** [comment]
I cannot run $ tests.sh or $ ./run.sh -web-interface=true successfully. 

It should be automatic now, you dont need flag

http://127.0.0.1:6420

go into ~/.skycoin and delete the old block chain. That is why you get that error I think. The genesis block has changed.
