### ISSUE TITLE
Node crash when ctrl+c while synchronizing blocks

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin#360]
Node crashed when I ctrl+c while blocks are downloading:
```
[skycoin.daemon:INFO] Shutdown pool
[skycoin.daemon:INFO] Saving Peer List
[skycoin.daemon:INFO] Shutdown peers
[skycoin.visor:INFO] close db
unexpected fault address 0x7fd55565838c
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fd55565838c pc=0x463d6a]

goroutine 39 [running]:
runtime.throw(0x88ed62, 0x5)
 /home/atomos/.gvm/gos/go1.7/src/runtime/panic.go:566 +0x95 fp=0xc420429590 sp=0xc420429570
runtime.sigpanic()
 /home/atomos/.gvm/gos/go1.7/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc4204295e8 sp=0xc420429590
runtime.memmove(0xc4202da050, 0x7fd55565838c, 0x44)
 /home/atomos/.gvm/gos/go1.7/src/runtime/memmove_amd64.s:186 +0x2da fp=0xc4204295f0 sp=0xc4204295e8
```

**Comment by iketheadore** [comment]
This is a graceful shutdown bug, will fix it.
