### ISSUE TITLE
createRawTx fails: ReadableOutputs.ToUxArray() changes hash

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin#929]
`ReadableOutputs.ToUxArray()`, which converts `visor.ReadableOutputs` to `coin.UxArray` for use in `spend()` construction, does not produce the correct `UxOut` values, resulting in an invalid hash.

Fix the method and add a test.

```go
func one() {
	unspents, err := CLIENT.GetUnspentOutputs([]string{"2dvVgeKNU7UHdvvBUVZXbBaxoTkpemo1cmg"})
	if err != nil {
		log.Panic(err)
	}

	inUxs, err := unspents.Outputs.SpendableOutputs().ToUxArray()
	if err != nil {
		log.Panic(err)
	}

	fmt.Printf("--------- %s\n", inUxs[0].Hash().Hex())
	fmt.Printf("-source:  %s\n", inUxs[0].Body.SrcTransaction.Hex())
	fmt.Printf("-address: %s\n", inUxs[0].Body.Address.String())
	fmt.Printf("-coins:   %d\n", inUxs[0].Body.Coins)
	fmt.Printf("-hours:   %d\n", inUxs[0].Body.Hours)

	/*
		--------- fd9f85e8ed4dd18d715513e6a65c5a00f662662ab7a27e9d3f7c01964e72f05b
		-source:  f57cb0a15fa4f0e6d0f65239593baf3197b99016624c83119180ef5bba7320f0
		-address: 2dvVgeKNU7UHdvvBUVZXbBaxoTkpemo1cmg
		-coins:   10000000
		-hours:   8286
	*/
}

func two() {
	unspents, err := CLIENT.GetUnspentOutputs([]string{"2dvVgeKNU7UHdvvBUVZXbBaxoTkpemo1cmg"})
	if err != nil {
		log.Panic(err)
	}

	inUxs := unspents.Outputs.SpendableOutputs()

	fmt.Printf("--------- %s\n", inUxs[0].Hash)
	fmt.Printf("-source:  %s\n", inUxs[0].SourceTransaction)
	fmt.Printf("-address: %s\n", inUxs[0].Address)
	fmt.Printf("-coins:   %s\n", inUxs[0].Coins)
	fmt.Printf("-hours:   %d\n", inUxs[0].Hours)

	/*
		--------- 169e7166515a4e308a9a1362e624d6e28b48d94e85fcd878995a70ddd168d7a2
		-source:  f57cb0a15fa4f0e6d0f65239593baf3197b99016624c83119180ef5bba7320f0
		-address: 2dvVgeKNU7UHdvvBUVZXbBaxoTkpemo1cmg
		-coins:   10.000000
		-hours:   8286
	*/
}
```

**Comment by skycoin-karl** [comment]
I created a small program demonstrating this bug.

```go
package main

import (
	"github.com/skycoin/skycoin/src/api/webrpc"
)

// this function converts the coin.ReadableOutputs type to coin.UxArray
func usingToUxArray(c *webrpc.Client, addr string) (string, error) {
	unspents, err := c.GetUnspentOutputs([]string{addr})
	if err != nil {
		return "", err
	}

	inUxs, err := unspents.Outputs.SpendableOutputs().ToUxArray()
	if err != nil {
		return "", err
	}

	return inUxs[0].Hash().Hex(), nil
}

// this function directly reads from the []visor.ReadableOutput type returned by
// unspents.Outputs.SpendableOutputs()
func notUsingToUxArray(c *webrpc.Client, addr string) (string, error) {
	unspents, err := c.GetUnspentOutputs([]string{addr})
	if err != nil {
		return "", err
	}

	// returns visor.ReadableOutputs which is an alias for
	// []visor.ReadableOutput
	inUxs := unspents.Outputs.SpendableOutputs()

	// visor.ReadableOutput.Hash
	return inUxs[0].Hash, nil
}

func main() {
	// this address contains 10 confirmed coins with no unconfirmed transactions
	addr := "2dvVgeKNU7UHdvvBUVZXbBaxoTkpemo1cmg"

	c := &webrpc.Client{Addr: "localhost:6430"}

	using, err := usingToUxArray(c, addr)
	if err != nil {
		panic(err)
	}

	notUsing, err := notUsingToUxArray(c, addr)
	if err != nil {
		panic(err)
	}

	// these should be equal
	println("USING:     " + using)
	println("NOT USING: " + notUsing)
}
```

**Comment by skycoin-karl** [comment]
`inUxs[0].Hash().Hex()` calls `coin.UxOut.Hash()` which is just:

```go
func (uo *UxOut) Hash() cipher.SHA256 {
	return uo.Body.Hash()
}
```

And `coin.UxOut.Body.Hash()` is:

```go
func (ub *UxBody) Hash() cipher.SHA256 {
	return cipher.SumSHA256(encoder.Serialize(ub))
}
```

I suspect the culprit is something weird happening with `encoder.Serialize(ub)`. All values in the `coin.UxBody` are equal to the values in `visor.ReadableOutput`, however, `coin.UxBody` is using Go types and not raw strings like `visor.ReadableOutput` (as shown in the first comment).

**Comment by skycoin-karl** [comment]
My suspicions about `encoder.Serialize(ub)` seem to be correct. Using the same address shown above, when calling `encoder.Serialize(ub)` it produces the `[]byte` output (in hex for readability):

```
f57cb0a15fa4f0e6d0f65239593baf3197b99016624c83119180ef5bba7320f000ebe7192de42bbd5916a765a8e809782150af31d080969800000000005e20000000000000
```

However, if we use this same `[]byte` data as the parameter for `coin.TransactionDeserialize(b []byte)` we get an `Invalid Transaction` error:

```
2018/02/01 09:34:12 Failed to deserialize transaction: Invalid transaction: Deserialization failed
panic: Failed to deserialize transaction: Invalid transaction: Deserialization failed

goroutine 1 [running]:
github.com/skycoin/skycoin/vendor/github.com/op/go-logging.(*Logger).Panicf(0xc42007adb0, 0x12e6a75, 0x25, 0xc420123c70, 0x1, 0x1)
        /Users/skycoin-karl/go/src/github.com/skycoin/skycoin/vendor/github.com/op/go-logging/logger.go:189 +0x17d
github.com/skycoin/skycoin/src/coin.MustTransactionDeserialize(0xc42023a0a0, 0x45, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/skycoin-karl/go/src/github.com/skycoin/skycoin/src/coin/transactions.go:288 +0x16b
main.main()
        /Users/skycoin-karl/bug/bug.go:68 +0x28f
```

**Comment by skycoin-karl** [comment]
`visor.ReadableOutput` gets the `Hash` field from the `hash` field in the JSON object below (created by webrpc):

```json
"outputs": {
    "head_outputs": [
        {
            "hash": "169e7166515a4e308a9a1362e624d6e28b48d94e85fcd878995a70ddd168d7a2",
            "time": 1517405925,
            "block_seq": 13159,
            "src_tx": "f57cb0a15fa4f0e6d0f65239593baf3197b99016624c83119180ef5bba7320f0",
            "address": "2dvVgeKNU7UHdvvBUVZXbBaxoTkpemo1cmg",
            "coins": "10.000000",
            "hours": 8286
        }
    ],
    "outgoing_outputs": [],
    "incoming_outputs": []
}
```

The question is how is that `hash` field created? And how is it different from the `coin.UxBody.Hash()` function?

**Comment by sky-90091** [comment]
Came across this issue yesterday. Note that master works fine.
